### ISSUE TITLE
Symfony 3 Support

### ISSUE THREAD

**Issue by seenudus** [theodo/TheodoEvolutionSessionBundle#27]
This project hasn't been very active for the past couple of years. Is it possible to have support for symfony 3 as well (currently composer.json sets the requirements for symfony2)?

I found out about this project from Alexander Ulyanov's blog: http://www.enotogorsk.ru/en/2014/07/26/integrating-legacy-session/

**Comment by benja-M-1** [comment]
Hi @seenudus, you're right, we were not very active on this bundle. Thanks to @jacobkiers the support for Symfony 3 is no available on the master branch. I'd love to have your feedback on this bundle with Symfony 3.

And thank you for pointing this blog post out, I didn't know it.
